mod.id = "dyeable_sulfur_blocks"
mod.name = "Dyeable Sulfur Blocks"
mod.group = "me.sshcrack.dyeable_sulfur_blocks"
mod.version = "0.1.0"
mod.channel_tag = ""
mod.description = "Dyeable Sulfur Blocks with colored steam for minecraft"
mod.authors = ["sshcrack"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "ARR"
mod.license.url = "https://github.com/sshcrack/dyed-sulfur-blocks/blob/main/LICENSE"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/sshcrack/dyed-sulfur-blocks/"
mod.homepage_url = "https://github.com/sshcrack/dyed-sulfur-blocks/"
mod.issues_url = "https://github.com/sshcrack/dyed-sulfur-blocks//issues"
mod.discord_url = ""
[[mod.pom.developers]]
id = "sshcrack"
name = "sshcrack"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0-alpha.8"
publish.additionalVersions = ["26.1.1", "26.1"]

[neoforge]

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
publish.additionalVersions = ["26.1.1", "26.1"]
